### ISSUE TITLE
rename directory tree twice ,the monitor info wrong

### ISSUE THREAD

**Issue by szlbwhj** [inotify-tools/inotify-tools#130]
**Describe the bug**
For a nested directory, the monitoring output of the first modification and then operation seems to be correct. After the second modification of the directory name, the path output of the tool monitoring appears wrong

**To Reproduce**
1. mkdir -p a1/a2/a3/a4/a5/a7/a8/a9
2. mv a1 b1
3. cd ..../a9
4. touch newfile
5. tools output a1/a2/a3/a4/a5/a7/a8/a9 not b1/a2/a3/a4/a5/a7/a8/a9

**Expected behavior**
tools output b1/a2/a3/a4/a5/a7/a8/a9

**Additional context**
maybe replace_filename function, delete tree_filename node during walk tree_filename

**Comment by ericcurtin** [comment]
Ha well spotted, it's like it assumes if we are referring to the same inode that the name of the directory hasn't changed. To reproduce, in one terminal:

<pre><font color="#295FCC"><b>~/tmp</b></font>$ inotifywait -r -m .
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
./ CREATE,ISDIR a1
./ OPEN,ISDIR a1
./ CLOSE_NOWRITE,CLOSE,ISDIR a1
./ OPEN,ISDIR a1
./ ACCESS,ISDIR a1
./ CLOSE_NOWRITE,CLOSE,ISDIR a1
./ MOVED_FROM,ISDIR a1
./ MOVED_TO,ISDIR b1
./b1/ MOVE_SELF 
./a1/a2/a3/a4/a5/a7/a8/a9/ CREATE newfile
./a1/a2/a3/a4/a5/a7/a8/a9/ OPEN newfile
./a1/a2/a3/a4/a5/a7/a8/a9/ ATTRIB newfile
./a1/a2/a3/a4/a5/a7/a8/a9/ CLOSE_WRITE,CLOSE newfile</pre>

In the other:

<pre><font color="#295FCC"><b>~/tmp</b></font>$ mkdir -p a1/a2/a3/a4/a5/a7/a8/a9
<font color="#295FCC"><b>~/tmp</b></font>$ mv a1 b1
<font color="#295FCC"><b>~/tmp</b></font>$ cd b1/a2/a3/a4/a5/a7/a8/a9
<font color="#295FCC"><b>~/tmp/b1/a2/a3/a4/a5/a7/a8/a9</b></font>$ touch newfile</pre>

a1 should say b1 in the first terminal/

**Comment by szlbwhj** [comment]
![image](https://user-images.githubusercontent.com/9426515/105976925-ba96ba80-60cb-11eb-9063-aaad92cdd0a6.png)
my case
