### ISSUE TITLE
Question: what is the use case for inotifywait daemon mode (-d) ?

### ISSUE THREAD

**Issue by qiulang** [inotify-tools/inotify-tools#144]
Hi,

This is a question and I am sorry I am asking it here. I guess if I ask at https://stackoverflow.com/ it may be just closed as opinion-based. I read thought the man page https://linux.die.net/man/1/inotifywait and googled it but I still don't see the use case of daemon mode for inotifywait.

With `-m`I can take immediate action based on the monitor output, but with `-d`  what can I do except for logging?

What is the use case for -d (except for logging)? 

BTW, can you add this information in man ?

Thanks

Qiulang

**Comment by ericcurtin** [comment]
The man page is correct although it could be more detailed. It runs the process as a daemon, since you referenced stackoverflow, here's a good answer that describes what is happening:

https://stackoverflow.com/a/17955149/2682012

Notice the `chdir / - Change the working directory of the daemon.` that's important to remember because filenames and paths are relative to / in daemon mode rather than your current directory.

It's not too different to performing something like:

`cd /; nohup inotifywait some_args..... &`

in an interactive shell in practice, although of course I'm leaving out some bits here. Here's two examples of inotifywait being used in that mode:

t/inotifywait-daemon-logs-chown.t
t/inotifywait-daemon-logs-to-relative-paths.t

**Comment by ericcurtin** [comment]
Would updating the documentation to this resolve your concerns @qiulang ?

```
Same as --monitor, except run in the background logging events to a file
that must be specified by --outfile. Implies --syslog. Daemonizing involves
running fork(), setsid(), chdir("/") (as opposed to your current working
directory), close().
```

**Comment by qiulang** [comment]
Hi thanks for answering my question. Actually my question was not about how daemon works or how to make daemon process correctly. My question was first trigger by this question and answer (I have the same problem) 

https://stackoverflow.com/questions/10533200/processing-data-with-inotify-tools-as-a-daemon/ 

The accepted answer said "You don't want to run inotifywait as a daemon in this case, because you want to continue process output from the command"  

So I was wondering what the use case for -d then.  Just logging the event ?

I did search issues and found this one https://github.com/inotify-tools/inotify-tools/issues/5  @rvoicilas there said

> As for why daemon mode is useful, I can see a couple of use cases, the most important one being - you want to record real-time when something happens, but you don't want to necessarily take action right away - you can run an offline piece of code that can process your logfile every couple of hours and make the required decisions.

But he said that 2013. Was that still valid ? Hence the question.

**Comment by ericcurtin** [comment]
There are use cases where you could use with "-d" and without "-d" and the end result would be similar. One example of where you would most likely use -d is if you were wrapping in a systemd/init script for starting as a service on boot etc.

Starting as a daemon ensures the process is unassigned it from the terminal it was executed, you don't have any ties to any file descriptors, you don't have any ties to any other processes (except for init), you also don't have any ties to the directory you executed in (because of the chdir("/")), you may have ties to a directory for other reasons than process start, this can prevent umounts, etc.

**Comment by ericcurtin** [comment]
Yes that answer is still valid

**Comment by qiulang** [comment]
Sorry if I may seem to be "fixated" on this,  my concern is with `-m` I can take immediate action based on the monitor output, but with `-d` I can't. **All the can do with** `-d` is to log what happened. 

You last comment seems to confirm this.

Apology again if I asked a dumb question.

**Comment by ericcurtin** [comment]
Not a dumb question in my eyes, it does sound like your use case would be more suited to not using daemon-mode.

Closing the issue.
