### ISSUE TITLE
Show inode number associated with watched resource in events

### ISSUE THREAD

**Issue by Kaprog** [inotify-tools/inotify-tools#145]
Hi,
Is it possible to include inode number of watched resource in event log? So `inotifywait -m` output would be similar to:
```
/tmp/ CREATE test 529561
/tmp/ DELETE test 529561
```
where `529561` is the inode number of `test` file. I am building database where these numbers are crucial and such feature would be really helpful. Thanks

**Comment by ericcurtin** [comment]
Not at present, but it would be a good idea to add as a --format option

**Comment by Kaprog** [comment]
Thanks for reply. So, if I understand correctly, such feature is technically possible and is just not yet implemented?

**Comment by ericcurtin** [comment]
Exactly

**Comment by Kaprog** [comment]
That's awesome. If time allows I will make a pull request. Thanks for help!

**Comment by Kaprog** [comment]
After short research I realize that in my case I don't really need inode number, but any number that will describe directory which contains file that was, for example, created. Watch descriptor is ideal for this purpose in my case.

But speaking of title of this issue. Getting inode of existing file isn't difficult (just combine directory name with file name, gather file descriptor and extract `st_ino`), but things are getting complicated when I would like to receive inode of deleted file (after inotify's DELETE event), because it's no longer possible to stat or open this file.

Therefor I think that adding feature of getting inode wouldn't be so helpful, because of partial lack of compatibility with inotify's events. If You don't agree or have better idea, please share. I will think about it tomorrow, and if nothing changes I will close this issue.

**Comment by ericcurtin** [comment]
I'm generally happy with any features added that solves your problem (in fact the more the merrier :smile: I'm sure others would benefit from this also) if:

- There's a automated test written.
- It doesn't interfere or break existing functionality.

Feel free to add a % format specifier for whatever option helps your use case. If that's both inode and watch_id great or just one of either great also! I think it's possible to create a list of all the inodes we are watching when we set up the watches to find the DELETE inode.

Personally, I'd like to see the inode thing added, because there's a couple of issues logged that refer to the wrong file name being printed after a rename, I think that's caused by an assumption in the code that an inodes filename doesn't change and which of course is false on a rename, we don't recreate an inode in that case in Unix.

But if a watch descriptor suits your needs, fine by me.

**Comment by Kaprog** [comment]
I would love to contribute to this repository, it helped me a lot. You're right creating list of inodes could resolve this issue. It would take some memory, especially when there's a lot of files in some directory, but still... could work. I will work on that.

**Comment by ericcurtin** [comment]
It's worth getting @amir73il @jankara s opinion on this, they maintain inotify in the kernel.  It would be nice if we could add inode unsigned long to inotify_event struct somehow without breaking anything, I notice the last element of that struct is a flexible char array.

It's useful for both the rename and delete case. The one gotcha I can think of is the hard link case where an inode has multiple filenames.

**Comment by amir73il** [comment]
@Kaprog please don't invest your time on inotify.
This legacy kernel interface is not going to be extended.
It has been (almost entirely) superseded by fanotify FAN_REPORT_DFID_NAME mode, which is supported in this tool since https://github.com/inotify-tools/inotify-tools/pull/134.
FAN_DELETE_SELF event provides the file handle of the deleted inode, which is a stronger unique identifier than st_ino.
You can populate you database with object unique file handles using the name_to_handle_at() syscall.

w.r.t rename races and filenames, see inotifytools_filename_from_watch() for a race
free implementation in fanotify "fid mode".

In any case, in current code, the tool handling of rename is racy and incorrect -
When matching MOVED_FROM/MOVED_TO events, the tool does not check the inotify cookie
and wrongly assumes the subsequent MOVED_FROM/MOVED_TO are matching events.
In fanotify, there is no rename cookie, but FAN_MOVE_SELF has the fid of the renamed
directory, so it can be used for race free update of a directories path database.

w.r.t CREATE, there is no file handle of the created inode in current fanotify interface,
but I have posted a patch set to try and address this deficiency:
https://lore.kernel.org/linux-fsdevel/CAOQ4uxjYDDk00VPdWtRB1_tf+gCoPFgSQ9O0p0fGaW_JiFUUKA@mail.gmail.com/
It is not clear how much this interface extension is needed, so I would love to get more feedback about real life use cases that require this sort of information in CREATE event.

**Comment by Kaprog** [comment]
@amir73il thank You for this information. fanotify sounds promising. I didn't know that inotify is discontinued. 

My use case was to create file index in database, so each change in file system should describe unique file (to rename, delete or create new entry in database). Now I can manage to get this uniqueness using watch descriptor and file name, so for this purpose I don't need inode in inotify event.

So to resolve this issue, it's better to use newer kernel and fanotify instead of inotify to get unique identifier. Everything is clear now for me. For now, I'll close this issue then, because it seems to be resolved (if I am wrong, please reopen).

In near future, if time allows I will make a pull request to add possibility to return watch descriptor in `--format` option. Thanks for all help!
