### ISSUE TITLE
mkdir -pv commands not being logged correctly

### ISSUE THREAD

**Issue by voncloft** [inotify-tools/inotify-tools#160]
I wrote a script to watch multiple directories: https://github.com/voncloft/Voncloft-Search/blob/master/voogle/new-scripts/searchengine.sh

The script inside that script I am having an issue with is: https://github.com/voncloft/Voncloft-Search/blob/master/voogle/new-scripts/add.sh

Whenever I execute code on my system for mkdir -pv for example

I would like for it to execute for a/b/c ...not just the last folder

Thanks

mkdir -pv /temp/a/b/c (a does not exist)
only "c" will be logged a and b are not put into mysql database at all.

Am I doing something wrong?

**Comment by auouymous** [comment]
I only get events for "a" when using `mkdir -p a/b/c` inside a watched directory.

```
-r, --recursive
       Newly created subdirectories will also be watched.
```

**Comment by voncloft** [comment]
> I only get events for "a" when using `mkdir -p a/b/c` inside a watched directory.
> 
> ```
> -r, --recursive
>        Newly created subdirectories will also be watched.
> ```

I already have the -r in my script..... Still the mkdir -p does not work..... Did you even click the links i provided?

**Comment by auouymous** [comment]
My comment confirmed the program **is** broken and -r is not working correctly. The newly created directories are added to the watch list and future actions do send events, but a creation event needs to be sent, or the man page should mention it isn't possible.

It is however broken differently for me being that it sends an event for "a", while you said it was "c" that was sent. It makes sense that it would send the event for "a" because "a" is created directly inside the watched directory. Are you sure it was "c" and not "a"?

**Comment by voncloft** [comment]
> My comment confirmed the program **is** broken and -r is not working correctly. The newly created directories are added to the watch list and future actions do send events, but a creation event needs to be sent, or the man page should mention it isn't possible.
> 
> It is however broken differently for me being that it sends an event for "a", while you said it was "c" that was sent. It makes sense that it would send the event for "a" because "a" is created directly inside the watched directory. Are you sure it was "c" and not "a"?

Apologies, i misinterpreted your post. 

Upon further investigation it is in fact a and not c

**Comment by voncloft** [comment]
also suppose folders a has files in it 

a/1.txt

a/2.txt

mv a b 

inotify will catch moving folder name a to b......but 1.txt and 2.txt are not "caught"

**Comment by auouymous** [comment]
Nothing happens to the files inside the directory for an event to be generated. And I don't think inotifywait should be modified to send events for them. If you need "events" for files and directories inside a moved/renamed directory, you should manually iterate the directory contents.

**Comment by voncloft** [comment]
No offense but that seems really cheesy and inefficient

How often in the real world do you go

Mkdir a

Mkdir a/b

Mkdir a/b/c

I'm not looking to redo 100s of my scripts.

My search engine that i wrote should be able to track where a file or directory goes while using this as a backend.

**Comment by auouymous** [comment]
Again, the `mkdir -p` issue should be fixed.

The `mv` issue is not how filesystems work. A directory is a list of names+pointers to files and directories inside it. When you rename a directory or file, only the name is changed. When moving a directory or file to another directory, only the name+pointer is moved. In both cases, the contents at the other end of the pointer are never touched. It would be inefficient to actually move the contents, or for inotifywait to send events for them.

A hardlink is a second name+pointer that references the same contents as the original name+pointer. Will the creation of that hardlink be added to your database? What happens when that hardlink is moved or renamed? What happens when the original link is removed (the hardlink **still** points to the contents, and those contents **still** exist)?

It isn't hard for you to detect a moved/renamed directory and walk its contents to update children in your database. But your database approach is flawed when it comes to hardlinks.
